### ISSUE TITLE
static-ui-content is not being created

### ISSUE THREAD

**Issue by noamanhesham** [jovanni-hernandez/docker-compose-nginx-flask-react-boilerplate#1]
static-ui-content that is supposed to be a shared folder between UI and API services is not being created in the root folder as expected.
Volume does exist:
local               docker-compose-nginx-flask-react-boilerplate_static-ui-content
 docker volume inspect docker-compose-nginx-flask-react-boilerplate_static-ui-content
[
    {
        "CreatedAt": "2020-04-04T12:44:03Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "docker-compose-nginx-flask-react-boilerplate",
            "com.docker.compose.version": "1.25.4",
            "com.docker.compose.volume": "static-ui-content"
        },
        "Mountpoint": "/var/lib/docker/volumes/docker-compose-nginx-flask-react-boilerplate_static-ui-content/_data",
        "Name": "docker-compose-nginx-flask-react-boilerplate_static-ui-content",
        "Options": null,
        "Scope": "local"
    }
]

However, for whatever reasons this folder static-ui-content doesn't exist after running "docker-compose up"

**Comment by jovanni-hernandez** [comment]
Thanks for reporting the issue - I'll take a look at this shortly.

**Comment by jovanni-hernandez** [comment]
Hey @noamanhesham I just gave it a test and it seems to work fine, even after two years of no changes (minus the sample web app that is cloned in /ui/Dockerfile* not working, but that's a separate issue). Are you using the right commands?

docker-compose -f docker-compose.dev.yaml build
docker-compose -f docker-compose.dev.yaml up -d

**Comment by noamanhesham** [comment]
Hey @jovanni-hernandez   I removed the dev file and left the prod , then changed the name to docker-compose.yml and ran docker-compose build and then run, will clone it again and build it without changing anything.
I will let you know shortly.
Thank you for your feedback.

**Comment by noamanhesham** [comment]
@jovanni-hernandez 
I have cloned your project:
```
git clone https://github.com/jovanni-hernandez/docker-compose-nginx-flask-react-boilerplate.git
```
then build it 
```
hnoaman@compose1_dev:~/projects/docker-compose-nginx-flask-react-boilerplate$ docker-compose -f docker-compose.dev.yaml build
```
then ran it:
```
docker-compose -f docker-compose.dev.yaml up -d
Creating volume "docker-compose-nginx-flask-react-boilerplate_static-ui-content" with default driver
Recreating docker-compose-nginx-flask-react-boilerplate_api_1 ... done
Creating docker-compose-nginx-flask-react-boilerplate_ui_1    ... done
Creating docker-compose-nginx-flask-react-boilerplate_proxy_1 ... done
```
check NGINX and it is up:
```
hnoaman@compose1_dev:~/projects/docker-compose-nginx-flask-react-boilerplate$ docker-compose -f docker-compose.dev.yaml ps
                        Name                                      Command               State          Ports
--------------------------------------------------------------------------------------------------------------------
docker-compose-nginx-flask-react-boilerplate_api_1     python app.py                    Up      5090/tcp
docker-compose-nginx-flask-react-boilerplate_proxy_1   nginx -g daemon off;             Up      0.0.0.0:8080->80/tcp
docker-compose-nginx-flask-react-boilerplate_ui_1      docker-entrypoint.sh yarn  ...   Up      3000/tcp
```
As per the logs here, it looks like build was not created:
```
hnoaman@compose1_dev:~/projects/docker-compose-nginx-flask-react-boilerplate$ docker-compose -f docker-compose.dev.yaml logs -f
Attaching to docker-compose-nginx-flask-react-boilerplate_proxy_1, docker-compose-nginx-flask-react-boilerplate_api_1, docker-compose-nginx-flask-react-boilerplate_ui_1
ui_1     | yarn run v1.22.4
ui_1     | $ react-scripts start '&'
ui_1     | ℹ ｢wds｣: Project is running at http://172.26.0.2/
ui_1     | ℹ ｢wds｣: webpack output is served from /
ui_1     | ℹ ｢wds｣: Content not from webpack is served from /app/public
ui_1     | ℹ ｢wds｣: 404s will fallback to /index.html
ui_1     | Starting the development server...
ui_1     |
ui_1     | Compiled successfully!
ui_1     |
ui_1     | You can now view @tiburon-security/petrichor-dashboard in the browser.
ui_1     |
ui_1     |   Local:            http://localhost:3000/
ui_1     |   On Your Network:  http://172.26.0.2:3000/
ui_1     |
ui_1     | Note that the development build is not optimized.
ui_1     | To create a production build, use yarn build.
ui_1     |
api_1    |  * Serving Flask app "app" (lazy loading)
api_1    |  * Environment: production
api_1    |    WARNING: This is a development server. Do not use it in a production deployment.
api_1    |    Use a production WSGI server instead.
api_1    |  * Debug mode: on
api_1    |  * Running on http://0.0.0.0:5090/ (Press CTRL+C to quit)
api_1    |  * Restarting with stat
api_1    |  * Debugger is active!
api_1    |  * Debugger PIN: 135-724-997
```
and because of that static-content folder that should be shared between api and proxy doesn't exist:
```
hnoaman@compose1_dev:~/projects/docker-compose-nginx-flask-react-boilerplate$ ls -la
total 32
drwxrwxr-x 6 hnoaman hnoaman 4096 Apr 13 16:35 .
drwxrwxr-x 6 hnoaman hnoaman 4096 Apr 13 16:35 ..
drwxrwxr-x 3 hnoaman hnoaman 4096 Apr 13 16:35 api
-rw-rw-r-- 1 hnoaman hnoaman  812 Apr 13 16:35 docker-compose.dev.yaml
-rw-rw-r-- 1 hnoaman hnoaman  667 Apr 13 16:35 docker-compose.prod.yaml
drwxrwxr-x 8 hnoaman hnoaman 4096 Apr 13 16:35 .git
drwxrwxr-x 2 hnoaman hnoaman 4096 Apr 13 16:35 proxy
drwxrwxr-x 2 hnoaman hnoaman 4096 Apr 13 16:35 ui
```
this time I didn't change anything.

Did I missed something? should the  -  static-ui-content:/ui folder "static-ui-content" be created under the project's root folder ?

**Comment by noamanhesham** [comment]
Where should I locate the build/ folder content after running the compose file? 
and how should nginx find the content of static-ui-content if it was not created under the directory 
`/projects/docker-compose-nginx-flask-react-boilerplate`
I appreciate your response.

**Comment by jovanni-hernandez** [comment]
Hey, couple of things:

1) this is an example from when I was a noobie at docker & compose, I don't think I'd actually use it knowing what I do now. Instead I'd probably collapse both my dev & prod environments into a single environment and use docker entry scripts to make any changes between the two environments 

2) static-ui-content is a docker "named volume" that isn't explicitly mapped to a folder on the host, meaning it's just letting docker handle storage allocation on the host, i.e. it won't be easy to find on the host. The following command should tell you where its hosted at: `docker volume inspect docker-compose-nginx-flask-react-boilerplate_static-ui-content`

3) static-ui-content isn't even used on the .dev yaml. Instead, create-react-app is started in dev mode so you can make changes and have the application hot reload - it's never actually manually compiled. In the UI dockerfile, you see that it's running the dev web server via `yarn start` which runs it over port 3000. Then in the proxy configuration file (/proxy/nginx-dev.conf), you see that for dev it's redirecting all traffic to that http://ui:3000 dev server. Contrast with the prod yaml, UI compiles the application to the static-ui-content docker named volume, and proxy merely serves those static files.

**Comment by noamanhesham** [comment]
@jovanni-hernandez 
So static-ui-content won't be created, instead it will be served from wherever it is in the host machine, to NGINX, is that correct? 
```
hnoaman@compose1_dev:~/projects/docker-compose-nginx-flask-react-boilerplate$ docker volume inspect docker-compose-nginx-flask-react-boilerplate_static-ui-content
[
    {
        "CreatedAt": "2020-04-13T18:59:54Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "docker-compose-nginx-flask-react-boilerplate",
            "com.docker.compose.version": "1.25.4",
            "com.docker.compose.volume": "static-ui-content"
        },
        "Mountpoint": "/var/lib/docker/volumes/docker-compose-nginx-flask-react-boilerplate_static-ui-content/_data",
        "Name": "docker-compose-nginx-flask-react-boilerplate_static-ui-content",
        "Options": null,
        "Scope": "local"
    }
]
```
here is the content of the volume.
```
hnoaman@compose1_dev:~/projects/docker-compose-nginx-flask-react-boilerplate$ sudo ls -al /var/lib/docker/volumes/docker-compose-nginx-flask-react-boilerplate_static-ui-content/_data
total 104
drwxr-xr-x 3 root root  4096 Apr 13 18:59 .
drwxr-xr-x 3 root root  4096 Apr 13 16:36 ..
-rw-r--r-- 1 root root 11696 Apr  4 12:43 asset-manifest.json
-rw-r--r-- 1 root root 24838 Apr  4 12:42 favicon.ico
-rw-r--r-- 1 root root  4789 Apr  4 12:43 index.html
-rw-r--r-- 1 root root  7736 Apr  4 12:43 precache-manifest.40bb20444968c5a116a8e315457b0f81.js
-rw-r--r-- 1 root root 12722 Apr  4 12:42 routes_menu_config.json
-rw-r--r-- 1 root root   958 Apr  4 12:42 sample_graph_data_api.json
-rw-r--r-- 1 root root  2590 Apr  4 12:42 sample_nested_table_data_api.json
-rw-r--r-- 1 root root  3556 Apr  4 12:42 sample_notifications_api.json
-rw-r--r-- 1 root root    73 Apr  4 12:42 sample_user_api.json
-rw-r--r-- 1 root root  1255 Apr  4 12:43 service-worker.js
drwxr-xr-x 5 root root  4096 Apr 13 18:59 static
```


That makes sense, thank you for your response.
